### ISSUE TITLE
Favor incluir tratamento de exceções

### ISSUE THREAD

**Issue by acenelio** [eliasnepo/bds-cap1#1]
Caro Elias, para o trabalho ficar 100%, favor incluir o tratamento de exceções com ControllerAdvice conforme aulas, ok? O projeto até este momento está retornando erro 500 quando informamos um id inexistente na requisição.

**Comment by eliasnepo** [comment]
Boa tarde professor, já adicionei um StandardError e agora tanto procurar quanto deletar um ID inexistente retorna erro 404 com o status, mensagem, etc. Obrigado.

> Caro Elias, para o trabalho ficar 100%, favor incluir o tratamento de exceções com ControllerAdvice conforme aulas, ok? O projeto até este momento está retornando erro 500 quando informamos um id inexistente na requisição.

**Comment by acenelio** [comment]
Excelente Elias! Parabéns pela dedicação.
